apiVersion: batch/v1
kind: Job
metadata:
  name: operator-dependencies-ns-creator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: operator-dependencies-ns-creator
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if kubectl get ns argo-events >/dev/null 2>&1; then
                echo "Namespace argo-events already exists."
              else
                echo "Creating namespace argo-events..."
                kubectl create ns argo-events
              fi
      restartPolicy: OnFailure
  backoffLimit: 3
